Login Page with Authentication
FrankKleiton/ifleads-frontend pull request #11
Opened 2020-07-21 20:15 UTC by hdev14

It was created:
 - Login page
 - Authentication
 - Auth reducer and Actions
 - and Alert to info invalid credentials

![image](https://user-images.githubusercontent.com/44510574/88102261-9f278180-cb75-11ea-9a8d-274d1bdddfad.png)

2020-07-21 20:19 UTC, hdev14 commented
When approved it will be necessary to remove the conflicts manually. xD

2020-07-22 19:17 UTC, FrankKleiton requested changes

2020-07-22 19:17 UTC, FrankKleiton commented on src/layouts/Auth/index.js
> +    asdfs
Remover 'asdfs'

2020-07-22 19:17 UTC, FrankKleiton commented on src/redux/auth/sagas.js
> +    api.defaults.headers.Authorization = `Baerer ${token}`;
Bearer ${token}

2020-07-22 19:17 UTC, FrankKleiton commented on src/redux/auth/sagas.js
> +    api.defaults.headers.Authorization = `Baerer ${payload.auth.token}`;
Bearer ${payload.auth.token}

2020-07-23 22:13 UTC, hdev14 commented on src/layouts/Auth/index.js
> +    asdfs
kkk

2020-07-24 16:59 UTC, FrankKleiton approved these changes

2020-07-24 22:25 UTC, merged